version: "3.9"

database_variables:
  environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web-app:
    build: .
    command: ./app/start_prod.sh
    volumes:
      - .:/app
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DEBUG_MODE=False
      - SECRET_KEY=NONPRODUCTIONKEY
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  live-chat:
    build: .
    command: sh -c "cd app && daphne -b 0.0.0.0 -p 8010 Masquerade.asgi:application"
    volumes:
      - .:/app
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DEBUG_MODE=False
      - SECRET_KEY=NONPRODUCTIONKEY
    ports:
      - "8010:8010"
    depends_on:
      - db
      - redis
  nginx:
    build: ./nginx/nginx_prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web-app
    volumes:
      - ./staticfiles:/staticfiles
      - ./media:/media
      - ./certs:/etc/app_certs
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
