version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web-app:
    build: .
    command: bash -c "app/start_cron.sh && python app/manage.py runserver 0:8000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DEBUG_MODE=True
      - SECRET_KEY=NONPRODUCTIONKEY
      - DJANGO_SETTINGS_MODULE=Masquerade.settings
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"