# Generated by Django 4.1 on 2022-10-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_message_review_entry_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='compressed_file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
