# Generated by Django 4.1 on 2022-10-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_image_compressed_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='compressed_file',
            new_name='mini_file',
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_file',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
