# Generated by Django 4.1 on 2022-10-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_compressed_file_image_mini_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='update_date',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Test desc', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='indexed',
            field=models.BooleanField(default=True, verbose_name='Is indexed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
