# Generated by Django 4.1 on 2022-10-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_entry_update_date_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identicon',
            field=models.ImageField(default='default', upload_to=''),
            preserve_default=False,
        ),
    ]
