# Generated by Django 4.1 on 2022-10-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_user_identicon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='File',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='attached_image',
        ),
        migrations.AddField(
            model_name='entry',
            name='attached_files',
            field=models.ManyToManyField(to='forum.file'),
        ),
    ]
