# Generated by Django 4.1 on 2022-10-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_entryfile_delete_file_alter_entry_attached_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryfile',
            name='mini_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='entryfile',
            name='original_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='entryfile',
            name='thumbnail_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
