# Generated by Django 4.1 on 2022-10-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_entryfile_mini_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryfile',
            old_name='mini_file',
            new_name='compressed_file',
        ),
        migrations.RemoveField(
            model_name='entryfile',
            name='thumbnail_file',
        ),
        migrations.RemoveField(
            model_name='entryfile',
            name='user',
        ),
        migrations.AlterField(
            model_name='entryfile',
            name='original_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
