# Generated by Django 4.1 on 2022-10-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_rename_mini_file_entryfile_compressed_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
