# Generated by Django 4.1 on 2022-10-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_remove_user_display_name_remove_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='indexed',
        ),
    ]
