# Generated by Django 4.1 on 2022-10-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_remove_thread_indexed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default=None, editable=False, max_length=30, null=True),
        ),
    ]
