# Generated by Django 4.1 on 2022-11-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_user_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='attached_files',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='replied_to',
        ),
        migrations.AddField(
            model_name='entry',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='which_cycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entryfile',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.entry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='cycle',
            field=models.IntegerField(default=-6),
        ),
        migrations.AddField(
            model_name='thread',
            name='popularity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.user'),
        ),
    ]
