# Generated by Django 4.1 on 2022-11-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_cycle_remove_entry_popularity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='popularity',
        ),
    ]
